In [1]:
import numpy as np
import tflearn
import tensorflow as tf
import random
import json
import pickle
from utils import clean_pattern, define_network, recurrent_neural_network , convolutional_network , bidirectional_rnn

Instructions for updating:
non-resource variables are not supported in the long term
curses is not supported on this machine (please install/reinstall curses for an optimal experience)


In [2]:
data_file = open('intents.json', encoding='utf-8').read()
data = json.loads(data_file)


In [3]:
# Some cleaning of data in intents.json
stemmed_words = []
tags = []
ignore_words = ['!', '?', '.']
corpus = []

for intent in data['intents']:
    for pattern in intent['patterns']:
        stemmed_pattern = clean_pattern(pattern, ignore_words)
        stemmed_words.extend(stemmed_pattern)
        corpus.append((stemmed_pattern, intent['tag']))
    if intent['tag'] not in tags:
        tags.append(intent['tag'])

# remove duplicates and sort
stemmed_words = sorted(list(set(stemmed_words)))
tags = sorted(list(set(tags)))
print(len(stemmed_words))
print(len(tags))
print(len(corpus))
print(stemmed_words)
print(tags)
print(corpus)

577
177
251
['(', ')', ',', '3a2ili', '3a9ar', '3aslema', '3i9ed', '3la', '3omomi', '5asa', '5tar', '7afel', '7osol', '7ouma', '9arar', '`', 'a', 'act', 'adv', 'advert', 'an', 'and', 'apply', 'ar', 'as', 'ask', 'attest', 'au', "aujourd'hui", 'aut', 'aux', 'aw', 'aw9at', 'awel', 'awra9', 'balad', 'baladiy', 'bch', 'be', 'beaucoup', 'bedhabt', 'bel', 'bin', 'bin2', 'bine2', 'bir', 'bon', 'bonjo', 'book', 'born', 'build', 'bur', 'bye', 'cadavr', 'calendry', 'can', 'candid', 'cart', 'ce', 'cert', 'chahedet', 'chang', 'chart', 'chehedet', 'chkoun', 'chniya', 'chorot', 'chorout', 'chourot', 'cit', 'citoy', 'collect', 'com', 'comfort', 'commun', 'conc', 'conclud', 'condit', 'conform', 'conformité', 'confort', 'connect', 'conseil', 'construct', 'construir', 'cont', 'contenu', 'contract', 'cop', 'corps', 'council', 'd', "d'illumination", "d'une", 'daft', 'dan', 'dat', 'day', 'de', 'deceas', 'decid', 'demand', 'demarc', 'demol', 'deposit', 'des', 'dhaw', 'do', 'docu', 'domain', 'du', 'duty', 'dw

In [4]:
# Creating numeric features and labels out of cleaned data
X = []
y = []
for item in corpus:
    bag = [] #array of 1 and 0. 1 if stemmed word is present in stemmed pattern
    stemmed_pattern = item[0]
    for w in stemmed_words:
        if w in stemmed_pattern:
            bag.append(1)
        else:
            bag.append(0)

    tags_row = [] #array of 1 and 0. 1 for current tag and for everything else 0.
    current_tag = item[1]
    for tag in tags:
        if tag == current_tag:
            tags_row.append(1)
        else:
            tags_row.append(0)

    #for each item in corpus, X will be array indicating stemmed words and y array indicating tags
    X.append(bag)
    y.append(tags_row) 

X = np.array(X)
y = np.array(y)
print(X)
print(y)

# saving variables in pickle to be used by main.py
with open('saved_variables.pickle', 'wb') as file:
    pickle.dump((stemmed_words, tags, ignore_words, X, y), file)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
# model = recurrent_neural_network(X, y)
model = define_network(X, y)
# model = convolutional_network(X, y)
# model = bidirectional_rnn(X, y)
model.fit(X, y, n_epoch=200, batch_size=8, show_metric=True) 
model.save("chatbot_model.tflearn")

Training Step: 5820  | total loss: 0.26436 | time: 0.174s
| Adam | epoch: 182 | loss: 0.26436 - acc: 0.9593 -- iter: 224/251
